$(function() {
    $(".btn1").click(function() {
        $("#dogPic").removeClass("dog_pic2")
        $("#dogPic").removeClass("dog_pic3")
        $("#dogPic").removeClass("dog_pic4")
        $("#dogPic").removeClass("dog_pic5")
        $("#dogPic").removeClass("dog_pic6")
        $("#dogPic").addClass("dog_pic1")
        $("#storyline_2").addClass("hide")
        $("#storyline_3").addClass("hide")
        $("#storyline_4").addClass("hide")
        $("#storyline_5").addClass("hide")
        $("#storyline_6").addClass("hide")
        $("#storyline_1").removeClass("hide")
    })
    $(".btn2").click(function() {
        $("#dogPic").removeClass("dog_pic1")
        $("#dogPic").removeClass("dog_pic3")
        $("#dogPic").removeClass("dog_pic4")
        $("#dogPic").removeClass("dog_pic5")
        $("#dogPic").removeClass("dog_pic6")
        $("#dogPic").addClass("dog_pic2")
        $("#storyline_1").addClass("hide")
        $("#storyline_3").addClass("hide")
        $("#storyline_4").addClass("hide")
        $("#storyline_5").addClass("hide")
        $("#storyline_6").addClass("hide")
        $("#storyline_2").removeClass("hide")
    })
    $(".btn3").click(function() {
        $("#dogPic").removeClass("dog_pic1")
        $("#dogPic").removeClass("dog_pic2")
        $("#dogPic").removeClass("dog_pic4")
        $("#dogPic").removeClass("dog_pic5")
        $("#dogPic").removeClass("dog_pic6")
        $("#dogPic").addClass("dog_pic3")
        $("#storyline_1").addClass("hide")
        $("#storyline_2").addClass("hide")
        $("#storyline_4").addClass("hide")
        $("#storyline_5").addClass("hide")
        $("#storyline_6").addClass("hide")
        $("#storyline_3").removeClass("hide")
    })
    $(".btn4").click(function() {
        $("#dogPic").removeClass("dog_pic1")
        $("#dogPic").removeClass("dog_pic2")
        $("#dogPic").removeClass("dog_pic3")
        $("#dogPic").removeClass("dog_pic5")
        $("#dogPic").removeClass("dog_pic6")
        $("#dogPic").addClass("dog_pic4")
        $("#storyline_1").addClass("hide")
        $("#storyline_2").addClass("hide")
        $("#storyline_3").addClass("hide")
        $("#storyline_5").addClass("hide")
        $("#storyline_6").addClass("hide")
        $("#storyline_4").removeClass("hide")
    })
    $(".btn5").click(function() {
        $("#dogPic").removeClass("dog_pic1")
        $("#dogPic").removeClass("dog_pic2")
        $("#dogPic").removeClass("dog_pic3")
        $("#dogPic").removeClass("dog_pic4")
        $("#dogPic").removeClass("dog_pic6")
        $("#dogPic").addClass("dog_pic5")
        $("#storyline_1").addClass("hide")
        $("#storyline_2").addClass("hide")
        $("#storyline_3").addClass("hide")
        $("#storyline_4").addClass("hide")
        $("#storyline_6").addClass("hide")
        $("#storyline_5").removeClass("hide")
    })
    $(".btn6").click(function() {
        $("#dogPic").removeClass("dog_pic1")
        $("#dogPic").removeClass("dog_pic2")
        $("#dogPic").removeClass("dog_pic3")
        $("#dogPic").removeClass("dog_pic4")
        $("#dogPic").removeClass("dog_pic5")
        $("#dogPic").addClass("dog_pic6")
        $("#storyline_1").addClass("hide")
        $("#storyline_2").addClass("hide")
        $("#storyline_3").addClass("hide")
        $("#storyline_4").addClass("hide")
        $("#storyline_5").addClass("hide")
        $("#storyline_6").removeClass("hide")
        $("#arrowDown1").removeClass("hide")
        $("#abandon1").animate({ height: '1100px' }, )
        $("#story_end").removeClass("click1")
    })
    $(".btn7").click(function() {
        $("#dogPic2").removeClass("dog_pic8")
        $("#dogPic2").removeClass("dog_pic9")
        $("#dogPic2").removeClass("dog_pic10")
        $("#dogPic2").removeClass("dog_pic11")
        $("#dogPic2").addClass("dog_pic7")
        $("#storyline_8").addClass("hide")
        $("#storyline_9").addClass("hide")
        $("#storyline_10").addClass("hide")
        $("#storyline_11").addClass("hide")
        $("#storyline_7").removeClass("hide")
    })
    $(".btn8").click(function() {
        $("#dogPic2").removeClass("dog_pic7")
        $("#dogPic2").removeClass("dog_pic9")
        $("#dogPic2").removeClass("dog_pic10")
        $("#dogPic2").removeClass("dog_pic11")
        $("#dogPic2").addClass("dog_pic8")
        $("#storyline_7").addClass("hide")
        $("#storyline_9").addClass("hide")
        $("#storyline_10").addClass("hide")
        $("#storyline_11").addClass("hide")
        $("#storyline_8").removeClass("hide")
    })
    $(".btn9").click(function() {
        $("#dogPic2").removeClass("dog_pic7")
        $("#dogPic2").removeClass("dog_pic8")
        $("#dogPic2").removeClass("dog_pic10")
        $("#dogPic2").removeClass("dog_pic11")
        $("#dogPic2").addClass("dog_pic9")
        $("#storyline_7").addClass("hide")
        $("#storyline_8").addClass("hide")
        $("#storyline_10").addClass("hide")
        $("#storyline_11").addClass("hide")
        $("#storyline_9").removeClass("hide")
    })
    $(".btn10").click(function() {
        $("#dogPic2").removeClass("dog_pic7")
        $("#dogPic2").removeClass("dog_pic8")
        $("#dogPic2").removeClass("dog_pic9")
        $("#dogPic2").removeClass("dog_pic11")
        $("#dogPic2").addClass("dog_pic10")
        $("#storyline_7").addClass("hide")
        $("#storyline_8").addClass("hide")
        $("#storyline_9").addClass("hide")
        $("#storyline_11").addClass("hide")
        $("#storyline_10").removeClass("hide")
    })
    $(".btn11").click(function() {
        $("#dogPic2").removeClass("dog_pic7")
        $("#dogPic2").removeClass("dog_pic8")
        $("#dogPic2").removeClass("dog_pic9")
        $("#dogPic2").removeClass("dog_pic10")
        $("#dogPic2").addClass("dog_pic11")
        $("#storyline_7").addClass("hide")
        $("#storyline_8").addClass("hide")
        $("#storyline_9").addClass("hide")
        $("#storyline_10").addClass("hide")
        $("#storyline_11").removeClass("hide")
        $("#arrowDown2").removeClass("hide")
        $("#abandon2").animate({ height: '1100px' }, )
        $("#story_end").removeClass("click2")
    })
    $(".btn12").click(function() {
        $("#dogPic3").removeClass("dog_pic13")
        $("#dogPic3").removeClass("dog_pic14")
        $("#dogPic3").removeClass("dog_pic15")
        $("#dogPic3").removeClass("dog_pic16")
        $("#dogPic3").addClass("dog_pic12")
        $("#storyline_13").addClass("hide")
        $("#storyline_14").addClass("hide")
        $("#storyline_15").addClass("hide")
        $("#storyline_16").addClass("hide")
        $("#storyline_12").removeClass("hide")
    })
    $(".btn13").click(function() {
        $("#dogPic3").removeClass("dog_pic12")
        $("#dogPic3").removeClass("dog_pic14")
        $("#dogPic3").removeClass("dog_pic15")
        $("#dogPic3").removeClass("dog_pic16")
        $("#dogPic3").addClass("dog_pic13")
        $("#storyline_12").addClass("hide")
        $("#storyline_14").addClass("hide")
        $("#storyline_15").addClass("hide")
        $("#storyline_16").addClass("hide")
        $("#storyline_13").removeClass("hide")
    })
    $(".btn14").click(function() {
        $("#dogPic3").removeClass("dog_pic12")
        $("#dogPic3").removeClass("dog_pic13")
        $("#dogPic3").removeClass("dog_pic15")
        $("#dogPic3").removeClass("dog_pic16")
        $("#dogPic3").addClass("dog_pic14")
        $("#storyline_12").addClass("hide")
        $("#storyline_13").addClass("hide")
        $("#storyline_15").addClass("hide")
        $("#storyline_16").addClass("hide")
        $("#storyline_14").removeClass("hide")
    })
    $(".btn15").click(function() {
        $("#dogPic3").removeClass("dog_pic12")
        $("#dogPic3").removeClass("dog_pic13")
        $("#dogPic3").removeClass("dog_pic14")
        $("#dogPic3").removeClass("dog_pic16")
        $("#dogPic3").addClass("dog_pic15")
        $("#storyline_12").addClass("hide")
        $("#storyline_13").addClass("hide")
        $("#storyline_14").addClass("hide")
        $("#storyline_16").addClass("hide")
        $("#storyline_15").removeClass("hide")
    })
    $(".btn16").click(function() {
        $("#dogPic3").removeClass("dog_pic12")
        $("#dogPic3").removeClass("dog_pic13")
        $("#dogPic3").removeClass("dog_pic14")
        $("#dogPic3").removeClass("dog_pic15")
        $("#dogPic3").addClass("dog_pic16")
        $("#storyline_12").addClass("hide")
        $("#storyline_13").addClass("hide")
        $("#storyline_14").addClass("hide")
        $("#storyline_15").addClass("hide")
        $("#storyline_16").removeClass("hide")
        $("#arrowDown3").removeClass("hide")
        $("#abandon3").animate({ height: '1100px' }, )
        $("#story_end").removeClass("click3")
    })
    $("#pick1").click(function() {
        $("#story_1").animate({ left: '0%' }, 1000)
        $("#story_2").animate({ left: '100%' }, 1000)
        $("#story_3").animate({ left: '200%' }, 1000)
        $("#arrowDown1").addClass("hide")
        $("#abandon2").animate({ height: '0px' }, )
        $("#abandon3").animate({ height: '0px' }, )
    })
    $("#pick2").click(function() {
        $("#story_1").animate({ left: '-100%' }, 1000)
        $("#story_2").animate({ left: '0%' }, 1000)
        $("#story_3").animate({ left: '100%' }, 1000)
        $("#arrowDown2").addClass("hide")
        $("#abandon1").animate({ height: '0px' }, )
        $("#abandon3").animate({ height: '0px' }, )

    })
    $("#pick3").click(function() {
        $("#story_1").animate({ left: '-200%' }, 1000)
        $("#story_2").animate({ left: '-100%' }, 1000)
        $("#story_3").animate({ left: '0%' }, 1000)
        $("#arrowDown3").addClass("hide")
        $("#abandon2").animate({ height: '0px' }, )
        $("#abandon1").animate({ height: '0px' }, )
    })
    let act1=Array.from(document.querySelectorAll("#story_Fir>div>a"))
    let act2=Array.from(document.querySelectorAll("#story_Sec>div>a"))
    let act3=Array.from(document.querySelectorAll("#story_Thr>div>a"))

    $.each(act1,function(){
        $(act1).click(function(){
            $("#story_Fir>div>a").removeClass("active")
            $(this).addClass("active")
        })
    })
    $.each(act2,function(){
        $(act2).click(function(){
            $("#story_Sec>div>a").removeClass("active")
            $(this).addClass("active")
        })
    })
    $.each(act3,function(){
        $(act3).click(function(){
            $("#story_Thr>div>a").removeClass("active")
            $(this).addClass("active")
        })
    })
})