$(function() {
    $(".btn1").click(function() {
        $("#dogPic").removeClass("dog_pic2")
        $("#dogPic").removeClass("dog_pic3")
        $("#dogPic").removeClass("dog_pic4")
        $("#dogPic").addClass("dog_pic1")
        $("#storyline_2").addClass("hide")
        $("#storyline_3").addClass("hide")
        $("#storyline_4").addClass("hide")
        $("#storyline_1").removeClass("hide")
    })
    $(".btn2").click(function() {
        $("#dogPic").removeClass("dog_pic1")
        $("#dogPic").removeClass("dog_pic3")
        $("#dogPic").removeClass("dog_pic4")
        $("#dogPic").addClass("dog_pic2")
        $("#storyline_1").addClass("hide")
        $("#storyline_3").addClass("hide")
        $("#storyline_4").addClass("hide")
        $("#storyline_2").removeClass("hide")
    })
    $(".btn3").click(function() {
        $("#dogPic").removeClass("dog_pic1")
        $("#dogPic").removeClass("dog_pic2")
        $("#dogPic").removeClass("dog_pic4")
        $("#dogPic").addClass("dog_pic3")
        $("#storyline_1").addClass("hide")
        $("#storyline_2").addClass("hide")
        $("#storyline_4").addClass("hide")
        $("#storyline_3").removeClass("hide")
    })
    $(".btn4").click(function() {
        $("#dogPic").removeClass("dog_pic1")
        $("#dogPic").removeClass("dog_pic2")
        $("#dogPic").removeClass("dog_pic3")
        $("#dogPic").addClass("dog_pic4")
        $("#storyline_1").addClass("hide")
        $("#storyline_2").addClass("hide")
        $("#storyline_3").addClass("hide")
        $("#storyline_4").removeClass("hide")
    })
    $(".btn5").click(function() {
        $("#dogPic2").removeClass("dog_pic6")
        $("#dogPic2").removeClass("dog_pic7")
        $("#dogPic2").addClass("dog_pic5")
        $("#storyline_6").addClass("hide")
        $("#storyline_7").addClass("hide")
        $("#storyline_5").removeClass("hide")
    })
    $(".btn6").click(function() {
        $("#dogPic2").removeClass("dog_pic5")
        $("#dogPic2").removeClass("dog_pic7")
        $("#dogPic2").addClass("dog_pic6")
        $("#storyline_5").addClass("hide")
        $("#storyline_7").addClass("hide")
        $("#storyline_6").removeClass("hide")
    })
    $(".btn7").click(function() {
        $("#dogPic2").removeClass("dog_pic5")
        $("#dogPic2").removeClass("dog_pic6")
        $("#dogPic2").addClass("dog_pic7")
        $("#storyline_5").addClass("hide")
        $("#storyline_6").addClass("hide")
        $("#storyline_7").removeClass("hide")
        $("#arrow2").removeClass("hide")
        $("#abandon").animate({ height: '1135px' }, )
    })
    $(".btn8").click(function() {
        $("#dogPic3").removeClass("dog_pic9")
        $("#dogPic3").removeClass("dog_pic10")
        $("#dogPic3").addClass("dog_pic8")
        $("#storyline_9").addClass("hide")
        $("#storyline_10").addClass("hide")
        $("#storyline_8").removeClass("hide")
    })
    $(".btn9").click(function() {
        $("#dogPic3").removeClass("dog_pic8")
        $("#dogPic3").removeClass("dog_pic10")
        $("#dogPic3").addClass("dog_pic9")
        $("#storyline_8").addClass("hide")
        $("#storyline_10").addClass("hide")
        $("#storyline_9").removeClass("hide")
    })
    $(".btn10").click(function() {
        $("#dogPic3").removeClass("dog_pic8")
        $("#dogPic3").removeClass("dog_pic9")
        $("#dogPic3").addClass("dog_pic10")
        $("#storyline_8").addClass("hide")
        $("#storyline_9").addClass("hide")
        $("#storyline_10").removeClass("hide")
    })

    $("#pick1").click(function() {
        $("#story_1").animate({ left: '0%' }, 1000)
        $("#story_2").animate({ left: '100%' }, 1000)
        $("#story_3").animate({ left: '200%' }, 1000)
    })
    $("#pick2").click(function() {
        $("#story_1").animate({ left: '-100%' }, 1000)
        $("#story_2").animate({ left: '0%' }, 1000)
        $("#story_3").animate({ left: '100%' }, 1000)

    })
    $("#pick3").click(function() {
        $("#story_1").animate({ left: '-200%' }, 1000)
        $("#story_2").animate({ left: '-100%' }, 1000)
        $("#story_3").animate({ left: '0%' }, 1000)
    })
})